# Configuration for Dolma Programming Languages
save_dir: "/path/to/save/directory"
dolma_json_dir: "/juice4/scr4/nlp/model-tracing/dolma_program_languages/json_files"
datasets:
  - "cpp"
  - "python"
  - "js"
model_architectures:
  - "llama"